CREATE TABLE IF NOT EXISTS "notifications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "message" NVARCHAR(1000) NOT NULL,
    "read" BIT NOT NULL DEFAULT 0,
    "created_at" DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_users FOREIGN KEY ("user_id") REFERENCES "users"("id"),
    CONSTRAINT fk_notifications_teams FOREIGN KEY ("team_id") REFERENCES "teams"("id")
);

CREATE TABLE IF NOT EXISTS "chat_rooms" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" NVARCHAR(255) NOT NULL UNIQUE,
    "team_id" BIGINT NOT NULL,
    CONSTRAINT fk_chat_rooms_teams FOREIGN KEY ("team_id") REFERENCES "teams"("id")
);

CREATE TABLE IF NOT EXISTS "messages" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "chat_room_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "content" NVARCHAR(2000) NOT NULL,
    "created_at" DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_chat_rooms FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms"("id"),
    CONSTRAINT fk_messages_users FOREIGN KEY ("user_id") REFERENCES "users"("id"),
    CONSTRAINT fk_messages_teams FOREIGN KEY ("team_id") REFERENCES "teams"("id")
);
