CREATE TABLE IF NOT EXISTS "customers" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    vat_number NVARCHAR(50),
    tax_code NVARCHAR(50),
    email NVARCHAR(255),
    phone NVARCHAR(50),
    address NVARCHAR(500),
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2
);

CREATE TABLE IF NOT EXISTS "articles" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    sku NVARCHAR(100) NOT NULL UNIQUE,
    unit_price DECIMAL(19, 2) NOT NULL,
    description NVARCHAR(1000),
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME2
);

CREATE TABLE IF NOT EXISTS "orders" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    order_date DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status NVARCHAR(50) NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES "customers"(id)
);

CREATE TABLE IF NOT EXISTS "order_items" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES "orders"(id),
    CONSTRAINT fk_order_items_article FOREIGN KEY (article_id) REFERENCES "articles"(id)
);

CREATE TABLE IF NOT EXISTS "customer_notes" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    note NVARCHAR(1000) NOT NULL,
    created_at DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_notes_customer FOREIGN KEY (customer_id) REFERENCES "customers"(id)
);

CREATE TABLE IF NOT EXISTS "article_stock" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    warehouse NVARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    updated_at DATETIME2 NOT NULL,
    CONSTRAINT fk_article_stock_article FOREIGN KEY (article_id) REFERENCES "articles"(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_articles_sku ON "articles" (sku);
