DROP ALL OBJECTS;

DROP TABLE IF EXISTS "document_history" CASCADE;
DROP TABLE IF EXISTS "invoice_lines" CASCADE;
DROP TABLE IF EXISTS "invoices" CASCADE;
DROP TABLE IF EXISTS "commissions" CASCADE;
DROP TABLE IF EXISTS "contracts" CASCADE;
DROP TABLE IF EXISTS "customers" CASCADE;
DROP TABLE IF EXISTS "articles" CASCADE;
DROP TABLE IF EXISTS "agents" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "teams" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;

CREATE TABLE "roles" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "teams" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    azure_id VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    role_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_users_roles FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_users_teams FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE "agents" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    agent_code VARCHAR(64) NOT NULL,
    team_role VARCHAR(128),
    CONSTRAINT fk_agents_users FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_agents_code UNIQUE (agent_code)
);

CREATE TABLE "contracts" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    start_date DATE NOT NULL,
    end_date DATE,
    total_value DECIMAL(19, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_contracts_agents FOREIGN KEY (agent_id) REFERENCES agents (id)
);

CREATE TABLE "customers" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    vat_number VARCHAR(50),
    tax_code VARCHAR(50),
    email VARCHAR(255),
    phone VARCHAR(50),
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX uq_customers_vat_number
    ON "customers" (vat_number);

CREATE UNIQUE INDEX uq_customers_tax_code
    ON "customers" (tax_code);

CREATE TABLE "articles" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    unit_price DECIMAL(19, 4) NOT NULL,
    vat_rate DECIMAL(5, 2) NOT NULL,
    unit_of_measure VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX uq_articles_code
    ON "articles" (code);

CREATE TABLE "invoices" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT,
    invoice_number VARCHAR(100) NOT NULL,
    customer_id BIGINT,
    customer_name VARCHAR(255) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE,
    status VARCHAR(50) NOT NULL,
    payment_date DATE,
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_invoices_contract FOREIGN KEY (contract_id) REFERENCES contracts (id),
    CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE UNIQUE INDEX uq_invoices_number
    ON "invoices" (invoice_number);

CREATE TABLE "invoice_lines" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    article_id BIGINT,
    article_code VARCHAR(100),
    description VARCHAR(1000) NOT NULL,
    quantity DECIMAL(19, 4) NOT NULL,
    unit_price DECIMAL(19, 4) NOT NULL,
    vat_rate DECIMAL(5, 2) NOT NULL,
    total DECIMAL(19, 4) NOT NULL,
    CONSTRAINT fk_invoice_lines_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_lines_article FOREIGN KEY (article_id) REFERENCES articles (id)
);

CREATE INDEX ix_invoice_lines_invoice
    ON "invoice_lines" (invoice_id);

CREATE TABLE "document_history" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(50) NOT NULL,
    document_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE "commissions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    total_commission DECIMAL(19, 2) NOT NULL,
    paid_commission DECIMAL(19, 2) NOT NULL,
    pending_commission DECIMAL(19, 2) NOT NULL,
    last_updated TIMESTAMP NOT NULL,
    CONSTRAINT fk_commission_contract FOREIGN KEY (contract_id) REFERENCES contracts (id),
    CONSTRAINT fk_commission_agent FOREIGN KEY (agent_id) REFERENCES agents (id),
    CONSTRAINT uq_commission_agent_contract UNIQUE (agent_id, contract_id)
);
